nextjs deployment
aws-samples/appmod-blueprints pull request #145
Opened 2024-11-13 23:22 UTC by shapirov103

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-11-13 23:31 UTC, shapirov103 commented on applications/next-js/deployment/dev/application.yml
> +              /unicorn: 8080
accessible on /unicorn

2024-11-13 23:47 UTC, 5herlocked requested changes

2024-11-13 23:47 UTC, 5herlocked commented on applications/next-js/lib/dynamo/index.ts
> +const API_URL = process.env.API_BASE_URL ?? 'http://rust-backend.team-rust,svc.cluster.local';
errant `,`

2024-11-14 00:34 UTC, elamaran11 commented on applications/next-js/lib/dynamo/index.ts
> +const API_URL = process.env.API_BASE_URL ?? 'http://rust-backend.team-rust,svc.cluster.local';
+1

2024-11-14 02:53 UTC, shapirov103 commented on applications/next-js/lib/dynamo/index.ts
> +const API_URL = process.env.API_BASE_URL ?? 'http://rust-backend.team-rust,svc.cluster.local';
fixed

2024-11-14 14:18 UTC, elamaran11 approved these changes
LGTM

2024-11-14 14:19 UTC, elamaran11 commented
@5herlocked You have a changes requested. Please approve, i can merge

2024-11-14 14:50 UTC, 5herlocked approved these changes

2024-11-14 14:51 UTC, merged