Add jupyterhub to management cluster
aws-samples/appmod-blueprints pull request #173
Opened 2024-12-30 19:33 UTC by zjaco13

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-12-30 20:01 UTC, zjaco13 commented
To test, run `setup-environments-local.sh`, then in argocd switch `kyverno-pss-policies-enforce-exceptions` to track from this branch.  Login at DOMAIN/jupyterhub with keycloak to start a session as user1

2024-12-31 15:39 UTC, elamaran11 requested changes
@zjaco13 This is AWSome work. I have a minor feedback on the approach. we have tomove the install to `aiml.tf` so people get this only when they optin aiml. Follow are the reqs for merging this PR:
1. Get the recommended approach updated
2. Get @hmuthusamy run this and confirm this works in this PR
3. Get the instructions of this section added to `AIML Delivery` module of our workshop.

2024-12-31 15:39 UTC, elamaran11 commented on platform/infra/terraform/mgmt/terraform/jupyterhub.tf
> +  manifest = {
I would like to move this step under this so people who opt in aiml only gets [this](https://github.com/aws-samples/appmod-blueprints/blob/main/platform/infra/terraform/mgmt/terraform/aiml-integrations.tf). This is part of componentizing approach.

2024-12-31 15:39 UTC, elamaran11 commented on .gitignore
> +prodplan
What are these plan files ignored?

2024-12-31 18:37 UTC, zjaco13 commented on .gitignore
> +prodplan
They are the outfiles from the terraform plan command in setup-environments.sh

2025-01-02 23:59 UTC, zjaco13 commented
> @zjaco13 This is AWSome work. I have a minor feedback on the approach. we have tomove the install to `aiml.tf` so people get this only when they optin aiml. Follow are the reqs for merging this PR:
> 
>     1. Get the recommended approach updated
> 
>     2. Get @hmuthusamy run this and confirm this works in this PR
> 
>     3. Get the instructions of this section added to `AIML Delivery` module of our workshop.

Tested by @hmuthusamy, will work on instructions next

2025-01-03 00:00 UTC, hmuthusamy commented
> @zjaco13 This is AWSome work. I have a minor feedback on the approach. we have tomove the install to `aiml.tf` so people get this only when they optin aiml. Follow are the reqs for merging this PR:
> 
>     1. Get the recommended approach updated
> 
>     2. Get @hmuthusamy run this and confirm this works in this PR
> 
>     3. Get the instructions of this section added to `AIML Delivery` module of our workshop.

@elamaran11  Validated the changes locally in a new setup. Works fine. [
![Screenshot 2025-01-02 at 4 49 33 PM](https://github.com/user-attachments/assets/38cc605b-a6a7-41fd-8941-f57a9ae27ce0)
](url)

2025-01-03 00:11 UTC, hmuthusamy approved these changes
LGTM

2025-01-03 00:11 UTC, hmuthusamy commented on platform/infra/terraform/mgmt/terraform/templates/argocd-apps/jupyterhub.yaml
> +                storageClass: gp2
Can we make it gp3?

2025-01-03 00:11 UTC, hmuthusamy commented on .gitignore
> +prodplan
This is part of the fix to use plan files and apply them in the script. Its good to add them to gitignore.

2025-01-03 15:02 UTC, elamaran11 commented
@hmuthusamy Thanks for the test, @zjaco13 Everything looks great, once we have the instructions in the workshop build, i will merge this.

2025-01-03 15:07 UTC, hmuthusamy commented
@zjaco13 Everything works fine but noticed when cleaning up, the jupyterhub helm chart creates a ELB for proxy service set on values yaml (Values.proxy.service.type “LoadBalancer” ). Do we need this or we can use the existing domain?

2025-01-06 16:40 UTC, hmuthusamy reviewed
LGTM

2025-01-07 16:23 UTC, elamaran11 approved these changes
LGTM. @zjaco13 The content needs a little polish. Please fix and test with TE in workshop studio. @hmuthusamy Once this PR is merged, Please test from TE in Workshop studio.

2025-01-07 16:23 UTC, merged